---
name: Docker build and deploy
on:
  push:
    branches:
      - main
      - develop
      - cicd/deepak
jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    environment: cicd/deepak
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          echo "Building Docker images"
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_REPO }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Images
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_REPO }}
  deploy:
    runs-on: ubuntu-latest
    environment: cicd/deepak
    needs: ["docker_build_push"]
    steps:
      # - name: Deploy quiz app
      #   run: |
      #     ssh ${{ vars.REMOTE_SSH_USER }}@${{ vars.REMOTE_SERVER_IP }} << EOF
      #     docker run -d -p ${{ vars.DOCKER_PORT }}:80 ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_REPO }}
      #     echo "Check Services..."
      #     docker ps
      #     EOF
      - name: Deploy Myquiz app using ssh action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.REMOTE_SERVER_IP }}
          username: ${{ vars.REMOTE_SSH_USER }}
          password: ${{ secrets.REMOTE_SSH_USERPASS }}
          script: |
            echo "Verifying remote user"
            id
            echo "login Docker hub"
            docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker run -d -p ${{ vars.DOCKER_PORT }}:80 ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_REPO }}
            sleep 60
            docker ps | grep dpaktamang/myquiz && echo RUNNING || echo FAILED; exit 1